# Generated by Django 6.0.2 on 2026-02-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto')], default='carro', max_length=10)),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('categoria', models.CharField(choices=[('passeio', 'Passeio'), ('utilitario', 'Utilitário')], default='passeio', max_length=10)),
                ('km_por_l', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
