# Generated by Django 6.0.2 on 2026-03-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_veiculo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('bicicleta', 'Bicicleta'), ('van', 'Van')], default='carro', max_length=10),
        ),
    ]
