# Generated by Django 6.0.2 on 2026-02-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField()),
                ('quilometragem', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('localizacao', models.CharField(max_length=100)),
                ('link_externo', models.URLField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='anuncios_fotos/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('aprovado', 'Aprovado'), ('pendente', 'Pendente'), ('rejeitado', 'Rejeitado'), ('removido', 'Removido')], default='aprovado', max_length=20)),
                ('data_moderacao', models.DateTimeField(blank=True, null=True)),
                ('motivo_moderacao', models.TextField(blank=True, null=True)),
                ('is_visivel', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('aprovado', 'Aprovado'), ('pendente', 'Pendente'), ('rejeitado', 'Rejeitado'), ('removido', 'Removido')], default='aprovado', max_length=20)),
                ('data_moderacao', models.DateTimeField(blank=True, null=True)),
                ('motivo_moderacao', models.TextField(blank=True, null=True)),
                ('is_visivel', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
