# Generated by Django 6.0.2 on 2026-02-09 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncioveiculo',
            name='moderado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuncios_moderados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postagem',
            name='moderado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postagens_moderadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
