# Generated by Django 6.0.2 on 2026-02-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_despesa', models.CharField(choices=[('alimentacao', 'Alimentação'), ('combustivel', 'Combustível'), ('manutencao', 'Manutenção do Veículo'), ('pedagio', 'Pedágio'), ('estacionamento', 'Estacionamento'), ('seguro', 'Seguro'), ('licenciamento', 'Licenciamento'), ('ferramentas', 'Ferramentas e Equipamentos'), ('comunicacao', 'Comunicação (Celular/Internet)'), ('uniforme', 'Uniforme e EPIs'), ('documentacao', 'Documentação e Licenças'), ('outros', 'Outros')], max_length=20)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data', models.DateField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='RegistroEntregaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rendimento', models.CharField(choices=[('unitario', 'Valor Unitário por Pacote'), ('diaria', 'Valor por Diária')], max_length=10)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('valor_diaria', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_pacotes', models.PositiveIntegerField()),
                ('pacotes_entregues', models.PositiveIntegerField()),
                ('pacotes_nao_entregues', models.PositiveIntegerField()),
                ('categoria_despesa', models.CharField(choices=[('nenhuma', 'Nenhuma Despesa'), ('alimentacao', 'Alimentação'), ('automotivo', 'Gasto Automotivo'), ('pedagio', 'Pedágio'), ('seguro', 'Seguro Mensal'), ('outros', 'Outros')], max_length=20)),
                ('valor_despesa', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('descricao_outros', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('quantidade_entregues', models.PositiveIntegerField()),
                ('quantidade_nao_entregues', models.PositiveIntegerField()),
                ('tipo_pagamento', models.CharField(choices=[('unitario', 'Valor Unitário por Pacote'), ('diaria', 'Valor por Diária'), ('por_hora', 'Valor por Hora'), ('fixo', 'Valor Fixo')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data', '-hora_inicio'],
            },
        ),
    ]
