# Generated by Django 6.0.2 on 2026-02-09 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro_entregadespesa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriadespesa',
            name='entregador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='despesa',
            name='categoria_personalizada',
            field=models.ForeignKey(blank=True, help_text='Categoria personalizada criada pelo usuário', null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro_entregadespesa.categoriadespesa'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='entregador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrotrabalho',
            name='entregador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='categoriadespesa',
            unique_together={('nome', 'entregador')},
        ),
    ]
