# Generated by Django 6.0.2 on 2026-03-01 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_entregadespesa', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroEntregaDespesa',
        ),
        migrations.AlterField(
            model_name='categoriadespesa',
            name='entregador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_despesa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrotrabalho',
            name='entregador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_trabalho', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrotrabalho',
            name='quantidade_entregues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registrotrabalho',
            name='quantidade_nao_entregues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registrotrabalho',
            name='tipo_pagamento',
            field=models.CharField(choices=[('por_entrega', 'Por entrega'), ('diaria', 'Valor por Diária'), ('por_hora', 'Valor por Hora'), ('fixo', 'Valor Fixo')], default='diaria', max_length=20),
        ),
        migrations.AddIndex(
            model_name='registrotrabalho',
            index=models.Index(fields=['entregador', 'data'], name='registro_en_entrega_b4171e_idx'),
        ),
    ]
