# Generated by Django 6.0.2 on 2026-02-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregador',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
