# Generated by Django 6.0.2 on 2026-03-01 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_entregador_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregador',
            name='email_codigo_expira_em',
        ),
        migrations.RemoveField(
            model_name='entregador',
            name='email_codigo_validacao',
        ),
        migrations.RemoveField(
            model_name='entregador',
            name='registration_code',
        ),
        migrations.RemoveField(
            model_name='entregador',
            name='registration_code_attempts',
        ),
        migrations.RemoveField(
            model_name='entregador',
            name='registration_code_blocked_until',
        ),
        migrations.RemoveField(
            model_name='entregador',
            name='registration_code_expires_at',
        ),
        migrations.AlterField(
            model_name='entregador',
            name='nome',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='CodigoVerificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('login_2fa', 'Login 2FA'), ('validacao_email', 'Validação de E-mail'), ('recuperacao_senha', 'Recuperação de Senha'), ('setup_2fa', 'Configuração 2FA')], default='login_2fa', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('tentativas', models.IntegerField(default=0)),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_seguranca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TwoFactorVerification',
        ),
    ]
